[DRAFT] Validation module
PnX-SI/GeoNature-citizen pull request #361
Opened 2023-09-14 17:47 UTC by LoanR

2023-09-14 18:05 UTC, camillemonchicourt commented
Le paramètre mais aussi les champs devrait parler de VALIDATE et non pas VERIFY.

2023-09-14 18:07 UTC, camillemonchicourt commented
Et pour être précis, je pense aussi qu'il faudrait parler de validation_status et non pas observation_status.

2023-10-06 18:23 UTC, LoanR commented
La PR me semble prête pour review.

Un précision concernant les migrations :
Avec le contexte et la configuration actuelle de SQLAlchemy, je n'ai pas réussi à le laisser générer seul les migrations.
La commande `flask db migrate` génère des fichiers de migration comme si c'était la première. Je n'ai pas non plus pu changer ça avec la mécanique du stamp. J'ai donc rédigé la migration à la main. Elle semble bien se comporter, un `upgrade` et un `downgrade` ne pose pas de soucis.

Pour mettre à jour la base, il faut :
- s'assurer que la précédente migration est bien la `e8c1cd57ad16` (ce qui est le cas sur dev, sinon, il faudra modifier cette dernière)
- se connecter au container `docker exec -it citizen-back /bin/bash`
- activer l'environnement `poetry shell`
- mettre à jour la DB `flask db upgrade`

Il y a un nouvel onglet "Validation" disponible si vous êtes validateur. On retrouvera ici **toutes** les observations non validées. Attention, si `taxhub` est activé, beaucoup de requêtes vont être envoyées pour obtenir les informations d'espèces et de programme ce qui sera très long si vous avez une grande base et que vous consultez la page juste après migration.
Pour éviter cela, vous pouvez jouer une commande SQL pour valider les observations ou bien vous rendre sur l'interface admin pour valider en bulk les observations cochées (action "With selected").

Merci pour vos retours !

2023-10-25 23:02 UTC, lpofredc requested changes

2023-10-25 23:02 UTC, lpofredc commented on frontend/src/app/programs/observations/validation-board/validation-board.component.html
> +            <input formControlName="id_observation" type="hidden" />
Sur une liste d'espèce longue (avec menu autoselect (cf. [seuil en config](https://github.com/PnX-SI/GeoNature-citizen/blob/93472eab0fefbbc6da2e612d2f01016749fb97bb/frontend/src/conf/app.config.ts.template#L63C1-L63C44)), le menu n'est pas fonctionnel

![Screenshot 2023-10-26 at 00-53-53 GeoNature-citizen](https://github.com/PnX-SI/GeoNature-citizen/assets/22891423/9c4979ce-4d5a-4fe7-ab3c-38866c0cd2e8)

2023-10-25 23:02 UTC, lpofredc commented on frontend/src/app/programs/observations/validation-board/validation-board.component.ts
> +import { Component, LOCALE_ID, Inject, OnInit } from '@angular/core';
Il est assez dommage et frustrant de ne pas pouvoir valider la donnée directement depuis la page d'enquête. N'est-ce pas possible?

2023-12-01 10:29 UTC, LoanR commented on backend/gncitizen/core/observations/admin.py
> +        observations_to_validate = db.session.query(ObservationModel).filter(ObservationModel.id_observation.in_(ids))
Modification faite dans le commit a263e3c

2023-12-01 10:30 UTC, LoanR commented on backend/gncitizen/core/observations/routes.py
> +                    to=UserModel.query.get(id_role).email,
Correction apportée par le commit 142f0fe

2023-12-01 10:31 UTC, LoanR commented on backend/gncitizen/core/observations/routes.py
> +                return {
Correction apportée par le commit cf5613a

2023-12-01 10:48 UTC, LoanR commented on backend/gncitizen/core/observations/routes.py
> +    if observation_to_update.one().id_role != current_user.id_user and not current_user.validator:
Comme j'utilise le update_observation, je n'ai pas voulu complexifier le if, j'ai préféré m'assurer qu'on était dans le cas spécial de la validation d'observation pour pouvoir vérifier que l'utilisateur a bien le droit de valider l'observation en question.
La vérification est faite à plusieurs endroits, notamment :
- https://github.com/PnX-SI/GeoNature-citizen/blob/490e25e3915ad956cd3eed941437ae49fba039e9/backend/gncitizen/core/observations/routes.py#L1114 pour le back donc une validation provenant d'un validateur propriétaire de ladite observation sera rejetée
- https://github.com/PnX-SI/GeoNature-citizen/blob/490e25e3915ad956cd3eed941437ae49fba039e9/frontend/src/app/programs/observations/obs.component.ts#L214 l'affichage de la modale ne se fait pas si les conditions ne sont pas remplies

2023-12-01 10:51 UTC, LoanR commented on frontend/src/app/programs/observations/list/list.component.html
Le fa-tag a été enlevé au profit d'un span click qui englobe le statut de validation. La modale de validation peut-être affichée en cliquant sur ce statut.
https://github.com/PnX-SI/GeoNature-citizen/blob/490e25e3915ad956cd3eed941437ae49fba039e9/frontend/src/app/programs/observations/list/list.component.html#L119-L122

2023-12-01 10:56 UTC, LoanR commented on frontend/src/app/programs/observations/validation-board/validation-board.component.html
> +            <input formControlName="id_observation" type="hidden" />
L'affichage avec la recherche a été corrigé par le bon usage du formatter d'input : https://github.com/PnX-SI/GeoNature-citizen/blob/490e25e3915ad956cd3eed941437ae49fba039e9/frontend/src/app/programs/observations/validation/validation.component.ts#L177-L180

2023-12-01 11:10 UTC, LoanR commented
J'ai ajouté les corrections demandées. J'attends de voir si tout est bon.
👋

2023-12-14 17:21 UTC, LoanR commented
Ah, je vois que j'ai des conflits depuis les derniers merges.
Je m'y penche au plus vite.

2023-12-18 00:03 UTC, lpofredc commented
> Ah, je vois que j'ai des conflits depuis les derniers merges. Je m'y penche au plus vite.

Je regarde pour ces conflits, merci. C'est lié à de devs menés en parrallèle.

2023-12-19 00:01 UTC, lpofredc commented
@LoanR , pourriez-vous regarder l'affichage des données sur la carte du module de validation, le chargement des données ne semble pas fonctionner correctement. 
Il y a également une autre erreur dans la console du navigateur, liée à la recherche d'un programme, inexistant puisque l'on est dans le module de validation:

```
ERROR TypeError: _this.programs is undefined
    ngOnInit obs.component.ts:104
```

Enfin, il faudrait éviter de charger toutes les données observateurs pour savoir quelles données sont validables. ça plombe les performances lorsque l'utilisateur a beaucoup d'observations. utilisé ici:

https://github.com/hypsug0/GeoNature-citizen/blob/1a2eba75fb3025e68eb7a6751cb924d66d0c666e/frontend/src/app/programs/observations/obs.component.ts#L220

Pour le reste, c'est bon pour moi.

2023-12-19 17:01 UTC, LoanR commented
> Affichage données sur la carte du module validation

Parfois, lorsque le nombre de d'observations à valider est élevé, la carte se charge avant que les observations (et donc leurs coordonnées) soient dans la page. Leaflet va donc tomber en erreur avec `Attempted to load an infinite number of tiles`.
Un fix simple est d'attendre que les observations soient chargées avant d'afficher la carte.
#bfd2172

2023-12-19 17:17 UTC, LoanR commented
> - [ ]  Erreur du frontend (recherche du programme inexistant)

OnInit est appelé dans observations-to-validate et surcharge celui de ObsComponent pour éviter de chercher inutilement un programme (comme dans le dashboard user-observations.
a6a4804

2023-12-19 17:21 UTC, LoanR commented
> - [ ] Chargement lourd des données de l'utilisateurs enregistré pour vérifier leur validabilité

Les appels aux observations de l'utilisateur ont été supprimés au profit d'une simple vérification de l'observer de l'observation.
20ee28f

2023-12-19 17:24 UTC, LoanR commented
> - [ ] Les données fraichement saisies sont validables par l'observateur enregistré

En se basant uniquement sur le username de l'observer, le retour de création d'une observation contient déjà toutes les informations pour savoir si l'utilisateur a le droit ou non de la valider.
20ee28f

2023-12-20 00:32 UTC, lpofredc commented
@LoanR, Serait-il possible de merger ma PR dans cette branche pour appliquer ces modifs sur la version corrigée? cela devrait résoudre les conflits. merci. 

En faisant quelques tests, j'ai une erreur lorsque l'on est dans le module, le clic sur l'icone du statut de validation n'ouvre pas le modal de validation et la console renvoie une erreur:

```
ERROR TypeError: _co.obsMapRef is undefined
    View_ObsToValidateComponent_3 ObsToValidateComponent.ngfactory.js:192
    Angular 5
    RxJS 5
    node_modules Angular
    onObsClick list.component.ts:147
    View_ObsListComponent_9 ObsListComponent.ngfactory.js:294
    Angular 12
```

![Capture d’écran du 2023-12-20 01-30-45](https://github.com/PnX-SI/GeoNature-citizen/assets/22891423/d5ac9af7-6463-470e-a1e3-856a8edd754f)

2023-12-20 09:55 UTC, hypsug0 commented
[pb identifié](https://github.com/PnX-SI/GeoNature-citizen/pull/361#issuecomment-1863658614) et résolu. Venait d'ailleurs :)

2024-02-12 09:41 UTC, closed without merging